### ISSUE TITLE
"boxplot" is not a registered controller

### ISSUE THREAD

**Issue by alissonmene** [sgratzl/chartjs-chart-boxplot#69]
When I compile my  app, it is getting a erro but developement is working ok.

**To Reproduce**

error below: 
react-dom.production.min.js:189 Error: "boxplot" is not a registered controller.
    at t.value (core.registry.js:178:13)
    at t.value (core.registry.js:66:17)
    at t.value (core.controller.js:455:42)
    at t.value (core.controller.js:508:33)
    at new t (core.controller.js:206:12)
    at P (chart.tsx:41:24)
    at chart.tsx:97:5
    at ol (react-dom.production.min.js:244:332)
    at Sc (react-dom.production.min.js:286:111)
    at react-dom.production.min.js:283:409
du @ react-dom.production.min.js:189
n.callback @ react-dom.production.min.js:189
Na @ react-dom.production.min.js:144
wl @ react-dom.production.min.js:262
El @ react-dom.production.min.js:260
bl @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
_c @ react-dom.production.min.js:281
cc @ react-dom.production.min.js:273
Vo @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267
react-dom.production.min.js:189 Error: "category" is not a registered scale.
    at t.value (core.registry.js:178:13)
    at t.value (core.registry.js:90:17)
    at core.controller.js:370:37
    at O (helpers.core.ts:149:12)
    at t.value (core.controller.js:355:5)
    at t.value (core.controller.js:561:10)
    at t.value (core.controller.js:495:10)
    at new t (core.controller.js:206:12)
    at P (chart.tsx:41:24)
    at chart.tsx:97:5
d

**Expected behavior**

**Screenshots**

**Context**

- Version:
    "@sgratzl/chartjs-chart-boxplot": "^4.1.2",
    "chart.js": "^4.3.0",
    "react-chartjs-2": "^5.2.0",
- Browser:
Chrome

**Additional context**

**Comment by sgratzl** [comment]
take a look at https://github.com/sgratzl/chartjs-chart-boxplot#esm-and-tree-shaking to properly register the controller and its elements
